# Generated by Django 2.2.6 on 2019-12-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20191205_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuario pode alterar parametro'), ('perm2', 'Permissao 2'), ('perm3', 'Permissao 3'))},
        ),
    ]
