# Generated by Django 2.2.6 on 2019-12-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20191208_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuario pode alterar parametro'), ('ver_dashboard', 'Pode ver o dashboard'), ('perm3', 'Permissao 3'))},
        ),
    ]
