# Generated by Django 2.2.6 on 2019-12-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20191204_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Deletar Clientes'),)},
        ),
    ]
